spring.application.name=Producer
transactions.batch.size =10
transactions.threads.corePoolSize=2
transactions.threads.maxPoolSize=4
transactions.threads.queueCapacity=100
transactions.threads.namePrefix=asyncTransactionExecutor
spring.kafka.topic.name=producer_topic
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.security.user.name=admin
spring.security.user.password=admin

#we can add DB properties here if required
